[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/test.php"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[start]
cmd = "php -S 0.0.0.0:${PORT:-3000} -t ."
port = "${PORT:-3000}"
